version: '3.7'

services:
  # 核心服务
  nestjs-bookmark:
    build:
      context: ../nestjs-server
      dockerfile: Dockerfile
    image: nestjs-bookmark:1.1
    environment:
      REDIS_HOST: "172.17.0.2"
      REDIS_PORT: 10069
      REDIS_PASSWORD: "redis"
      SONIC_HOUST: "172.17.0.2"
    ports:
      - "10004:3000" # minio api server