version: '3.7'

services:
  # 核心服务
  go-bookmark:
    build:
      context: ../go-server
      dockerfile: Dockerfile
    image: go-bookmark:1.1
    environment:
      REDIS_ADDRESS: "172.16.10.253:6379"
      REDIS_AUTH: ""
      REDIS_DB: "1"
      SONIC_HOST: "172.16.10.185"
      SONIC_PORT: "1491"
      SONIC_PASSWORD: "SecretPassword"
    ports:
      - "10004:8080" # minio api server
