version: '3.7'

services:
  # redisSearch搜索服务
  redissearch:
    image: redislabs/redisearch:latest
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - rs_data:/data
    ports:
      - "6380:6379"
  # 核心服务
  go-bookmark:
    build:
      context: ../go-server
      dockerfile: Dockerfile
    image: go-bookmark:1.1
    environment:
      REDIS_ADDRESS: "172.17.0.2:10069"
      REDIS_AUTH: "redis"
      REDIS_DB: "2"
      SONIC_HOST: "172.17.0.2"
      SONIC_PORT: "1491"
      SONIC_PASSWORD: "SecretPassword"
    ports:
      - "10004:8080" # minio api server
